### ISSUE TITLE
Error: Program type already present: com.vidyo.LmiDeviceManager.LmiAudioPlaybackDevice 

### ISSUE THREAD

**Issue by srijith1979** [Vidyo/vidyo.io-custom-connector-android#1]
Hi Team,

The app which I work on references two libraries and each of these libraries includes com.vidyo.LmiDeviceManager

I am running into the above error when I try to build my android app.

Your help on this will be greatly appreciated. Please find the below screenshot for reference. Thanks.

<img width="1132" alt="Screen Shot 2019-12-03 at 5 25 44 PM" src="https://user-images.githubusercontent.com/16881321/70098823-cfc0a800-15f2-11ea-9a1d-6282ab16d3a8.png">

**Comment by tmelko-vidyo** [comment]
It seems like you are trying to link VidyoClient twice from different modules under one project. You are not allowed to do that since Dex will fire an error (conflict). You can create one more module beneath and link it as a dependency so VidyoClient is not getting integrated twice.

**Comment by srijith1979** [comment]
Well, that is something out of my control.

The 2 modules in our app uses are the paid ones. Each of these modules uses Vidyo.  One of the requirements from Vidyo is to include some classes under `com.vidyo.LmiDeviceManager` package. Hence modules use the same classes (kind of copy-paste), and when I try to build my app with these 2 modules included, I get the same error above because of this duplicate classes.

It would be nice if Vidyo could build a separate library with the classes under `com.vidyo.LmiDeviceManager`.

Your help on this will be greatly appreciated. Thanks

**Comment by tmelko-vidyo** [comment]
Please reach out to us via customer support. It seems like you are referring to the VidyoWorks platform when this Github repo is Vidyo.io related.
